name: Go CI

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main", "develop"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:7.0
        env:
          MONGO_INITDB_ROOT_USERNAME: ${{ secrets.MONGO_CI_USERNAME }}
          MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGO_CI_PASSWORD }}
          MONGO_INITDB_DATABASE: water_monitoring_test
        ports:
          - 27017:27017

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Install dependencies
        run: go mod download

      - name: Build application
        run: go build -v ./...

      - name: Run automated teste with coverage
        env:
          MONGO_URI: "mongodb://${{secrets.MONGO_CI_USERNAME}}:${{secrets.MONGO_CI_PASSWORD}}@localhost:27017/?authSource=admin"
        run: |
          go test -v -coverprofile=coverage.out ./...
          go tool cover -func=coverage.out
